### ISSUE TITLE
Not working on Unity 5.3.4f1

### ISSUE THREAD

**Issue by umerkakar** [MicroGSD/RoadArchitect#6]
Hello,
I have imported RoadArchitect into my Unity 5.3.4f1. All files are imported. But it;s not showing the menu. And in console, I can see the error. 
![screenshot_2](https://cloud.githubusercontent.com/assets/11842713/26277701/9d72ffa0-3da6-11e7-8480-82ac51dae79c.png)

**Comment by voblivion** [comment]
Hi !
Have you tried using the .unitypackage release ? (DL it here : https://github.com/MicroGSD/RoadArchitect/releases). (Took me some time to find it, should be on README I think).
Victor

**Comment by umerkakar** [comment]
Thanks Victor,
I think, i was wrong. I am new to gaming and Unity. I think made a mistake. That I have downloaded source code and then import scripts directly into unity. And I think that is the reason things are not working. I was not aware about package of unity that is available on the link, you provided above. Downloading it. I will update you, what will happen after importing it.

Umer Sharif

**Comment by umerkakar** [comment]
Hello again.
I have installed package now as downloaded from link above. It still showing an error. I think you have to look into it. And I can't see menu item for the Road Architect in unity.
** Assets/RoadArchitect/GSDRoad.cs(538,53): error CS0234: The type or namespace name `Profiling' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference? **

![screenshot_3](https://cloud.githubusercontent.com/assets/11842713/26283986/0fe0b862-3e4b-11e7-88d5-6d61d9652640.png)

**Comment by TomOR1** [comment]
@umerkakar, the reason why it doesn't exist is that it doesn't exist.

before you look further down in the comment try and import the unity standard assets then if that doesn't work then do the following:

you now have 2 options:

1: delete GSDRoad.cs which is a core script and can't be deleted without consequences

2: update Unity

adv/disadv of updating unity:

adv: you can use the post processing in 5.6, you'll probably fix the issue

disadv: you have to press a few buttons

Hope this solves your issue!!

**Comment by umerkakar** [comment]
I had standard assets installed. And it was properly imported. 

Now I have latest version of unity 5.6.1, where its working fine. without any issue.
